-- ─────────────────────────────────────────────────────────────────────────────
-- OAU WGTBAM — Supabase Schema
-- Run this entire file in: Supabase Dashboard → SQL Editor → New Query
-- ─────────────────────────────────────────────────────────────────────────────

-- 1. QUESTIONS TABLE
-- Stores the quiz question bank. The admin manages this via the Supabase table editor.
-- difficulty_level: 2 = easy (questions 1-4), 3 = hard (questions 5-15)
create table if not exists public.questions (
  id          bigint generated by default as identity primary key,
  question    text        not null,
  option_a    text        not null,
  option_b    text        not null,
  option_c    text        not null,
  option_d    text        not null,
  answer      text        not null check (answer in ('a', 'b', 'c', 'd')),
  difficulty_level integer not null check (difficulty_level in (2, 3)),
  created_at  timestamptz not null default now()
);

-- 2. USERS TABLE
-- Stores event registrations (participants and attendees).
create table if not exists public.users (
  id          bigint generated by default as identity primary key,
  name        text        not null,
  email       text        not null unique,
  faculty     text,
  department  text,
  phone       text,
  reg_type    text        not null check (reg_type in ('participant', 'attendee')),
  created_at  timestamptz not null default now()
);

-- ─── Row Level Security ───────────────────────────────────────────────────────
-- We use the anon key from the client, so we allow public reads and inserts.
-- This is fine for a closed event app. Tighten these if needed.

alter table public.questions enable row level security;
alter table public.users     enable row level security;

-- Allow anyone to read questions (needed to fetch during the game)
create policy "Public can read questions"
  on public.questions for select
  using (true);

-- Allow anyone to insert users (registration form is public)
create policy "Public can register"
  on public.users for insert
  with check (true);

-- Allow anyone to read users (needed for the analytics page)
-- If you want to lock this down, remove this policy and use a server-side route instead.
create policy "Public can read users"
  on public.users for select
  using (true);

-- ─── Seed: sample questions ───────────────────────────────────────────────────
-- Replace or extend these with your real question bank.
-- difficulty_level 2 = shown for prize levels 1-4
-- difficulty_level 3 = shown for prize levels 5-15

insert into public.questions (question, option_a, option_b, option_c, option_d, answer, difficulty_level) values
  ('What is the capital of France?',                    'Berlin',           'Madrid',             'Paris',              'Rome',               'c', 2),
  ('Which planet is known as the Red Planet?',          'Mars',             'Venus',               'Jupiter',            'Saturn',             'a', 2),
  ('What is the chemical symbol for water?',            'Wo',               'Wa',                 'H2O',                'W',                  'c', 2),
  ('Who painted the Mona Lisa?',                        'Van Gogh',         'Leonardo da Vinci',  'Picasso',            'Michelangelo',       'b', 2),
  ('Which country is known as the Land of the Rising Sun?', 'China',        'Japan',              'India',              'Thailand',           'b', 3),
  ('What is the largest mammal in the world?',          'Elephant',         'Giraffe',            'Blue whale',         'Hippopotamus',       'c', 3),
  ('Who discovered penicillin?',                        'Isaac Newton',     'Alexander Fleming',  'Albert Einstein',    'Marie Curie',        'b', 3),
  ('What is the chemical symbol for gold?',             'Go',               'Ag',                 'Au',                 'Gl',                 'c', 3),
  ('Which is the smallest bone in the human body?',     'Femur',            'Cranium',            'Stapes',             'Fibula',             'c', 3),
  ('Who wrote Romeo and Juliet?',                       'Jane Austen',      'Shakespeare',        'Charles Dickens',    'Tolstoy',            'b', 3),
  ('What is the currency of Japan?',                    'Yen',              'Rupee',              'Dollar',             'Euro',               'a', 3),
  ('Which planet is known as the Blue Planet?',         'Mars',             'Venus',              'Earth',              'Jupiter',            'c', 3),
  ('Who wrote To Kill a Mockingbird?',                  'Mark Twain',       'Harper Lee',         'J.K. Rowling',       'Hemingway',          'b', 3),
  ('What is the largest ocean on Earth?',               'Atlantic',         'Indian',             'Arctic',             'Pacific',            'd', 3),
  ('Which country has the largest population?',         'India',            'USA',                'China',              'Brazil',             'c', 3);
