import { Question } from "@/types";

export const values = [
  { value: 15, amount: "₦1,000,000" },
  { value: 14, amount: "₦500,000" },
  { value: 13, amount: "₦300,000" },
  { value: 12, amount: "₦150,000" },
  { value: 11, amount: "₦75,000" },
  { value: 10, amount: "₦50,000" },
  { value: 9, amount: "₦30,000" },
  { value: 8, amount: "₦20,000" },
  { value: 7, amount: "₦10,000" },
  { value: 6, amount: "₦7,000" },
  { value: 5, amount: "₦5,000" },
  { value: 4, amount: "₦3,000" },
  { value: 3, amount: "₦2,000" },
  { value: 2, amount: "₦1,000" },
  { value: 1, amount: "₦500" },
];

export const QuestionArr: Question[] = [
  {
    question:
      "Which of the following is not a part of the seven wonder of the ancient world?",
    option1: "The Statue of Zues",
    option2: "The Great Pyramid of Giza",
    option3: "The Effiel Tower",
    option4: "The Colossus of Rhodes",
    answer: "The Effiel Tower",
  },
  {
    question: "What is the capital of France?",
    option1: "Berlin",
    option2: "Madrid",
    option3: "Paris",
    option4: "Rome",
    answer: "Paris",
  },
  {
    question: "Who wrote 'Romeo and Juliet'?",
    option1: "William Shakespeare",
    option2: "Jane Austen",
    option3: "Charles Dickens",
    option4: "Leo Tolstoy",
    answer: "William Shakespeare",
  },
  {
    question: "Which planet is known as the Red Planet?",
    option1: "Mars",
    option2: "Venus",
    option3: "Jupiter",
    option4: "Saturn",
    answer: "Mars",
  },
  {
    question: "What is the chemical symbol for water?",
    option1: "Wo",
    option2: "Wa",
    option3: "H2O",
    option4: "W",
    answer: "H2O",
  },
  {
    question: "Who painted the Mona Lisa?",
    option1: "Vincent van Gogh",
    option2: "Leonardo da Vinci",
    option3: "Pablo Picasso",
    option4: "Michelangelo",
    answer: "Leonardo da Vinci",
  },
  {
    question: "Which country is known as the Land of the Rising Sun?",
    option1: "China",
    option2: "Japan",
    option3: "India",
    option4: "Thailand",
    answer: "Japan",
  },
  {
    question: "What is the largest mammal in the world?",
    option1: "Elephant",
    option2: "Giraffe",
    option3: "Blue whale",
    option4: "Hippopotamus",
    answer: "Blue whale",
  },
  {
    question: "Which country is famous for the Great Wall?",
    option1: "China",
    option2: "Russia",
    option3: "India",
    option4: "Egypt",
    answer: "China",
  },
  {
    question: "What is the currency of Japan?",
    option1: "Yen",
    option2: "Rupee",
    option3: "Dollar",
    option4: "Euro",
    answer: "Yen",
  },
  {
    question: "Who discovered penicillin?",
    option1: "Isaac Newton",
    option2: "Alexander Fleming",
    option3: "Albert Einstein",
    option4: "Marie Curie",
    answer: "Alexander Fleming",
  },
  {
    question: "Which planet is known as the Blue Planet?",
    option1: "Mars",
    option2: "Venus",
    option3: "Earth",
    option4: "Jupiter",
    answer: "Earth",
  },
  {
    question: "Who wrote 'To Kill a Mockingbird'?",
    option1: "Mark Twain",
    option2: "Harper Lee",
    option3: "J.K. Rowling",
    option4: "Ernest Hemingway",
    answer: "Harper Lee",
  },
  {
    question: "Which country is known as the Land of Fire and Ice?",
    option1: "Iceland",
    option2: "Greenland",
    option3: "Australia",
    option4: "Norway",
    answer: "Iceland",
  },
  {
    question: "What is the chemical symbol for gold?",
    option1: "Go",
    option2: "Ag",
    option3: "Au",
    option4: "Gl",
    answer: "Au",
  },
  // {
  //   question: "Who invented the telephone?",
  //   option1: "Thomas Edison",
  //   option2: "Alexander Graham Bell",
  //   option3: "Nikola Tesla",
  //   option4: "Albert Einstein",
  //   answer: "Alexander Graham Bell",
  // },
  // {
  //   question: "Which is the smallest bone in the human body?",
  //   option1: "Femur",
  //   option2: "Cranium",
  //   option3: "Stapes",
  //   option4: "Fibula",
  //   answer: "Stapes",
  // },
  // {
  //   question: "Which country is known as the Land of the Rising Sun?",
  //   option1: "China",
  //   option2: "Japan",
  //   option3: "India",
  //   option4: "Thailand",
  //   answer: "Japan",
  // },
  // {
  //   question: "What is the chemical symbol for water?",
  //   option1: "Wo",
  //   option2: "Wa",
  //   option3: "H2O",
  //   option4: "W",
  //   answer: "H2O",
  // },
  // {
  //   question: "Who painted the Mona Lisa?",
  //   option1: "Vincent van Gogh",
  //   option2: "Leonardo da Vinci",
  //   option3: "Pablo Picasso",
  //   option4: "Michelangelo",
  //   answer: "Leonardo da Vinci",
  // },
  // {
  //   question: "Which country is known as the Land of the Rising Sun?",
  //   option1: "China",
  //   option2: "Japan",
  //   option3: "India",
  //   option4: "Thailand",
  //   answer: "Japan",
  // },
  // {
  //   question: "What is the chemical symbol for water?",
  //   option1: "Wo",
  //   option2: "Wa",
  //   option3: "H2O",
  //   option4: "W",
  //   answer: "H2O",
  // },
  // {
  //   question: "Who painted the Mona Lisa?",
  //   option1: "Vincent van Gogh",
  //   option2: "Leonardo da Vinci",
  //   option3: "Pablo Picasso",
  //   option4: "Michelangelo",
  //   answer: "Leonardo da Vinci",
  // },
  // {
  //   question: "Which country is known as the Land of the Rising Sun?",
  //   option1: "China",
  //   option2: "Japan",
  //   option3: "India",
  //   option4: "Thailand",
  //   answer: "Japan",
  // },
  // {
  //   question: "What is the chemical symbol for water?",
  //   option1: "Wo",
  //   option2: "Wa",
  //   option3: "H2O",
  //   option4: "W",
  //   answer: "H2O",
  // },
  // {
  //   question: "Who painted the Mona Lisa?",
  //   option1: "Vincent van Gogh",
  //   option2: "Leonardo da Vinci",
  //   option3: "Pablo Picasso",
  //   option4: "Michelangelo",
  //   answer: "Leonardo da Vinci",
  // },
  // {
  //   question: "Which country is known as the Land of the Rising Sun?",
  //   option1: "China",
  //   option2: "Japan",
  //   option3: "India",
  //   option4: "Thailand",
  //   answer: "Japan",
  // },
  // {
  //   question: "What is the chemical symbol for water?",
  //   option1: "Wo",
  //   option2: "Wa",
  //   option3: "H2O",
  //   option4: "W",
  //   answer: "H2O",
  // },
  // {
  //   question: "Who painted the Mona Lisa?",
  //   option1: "Vincent van Gogh",
  //   option2: "Leonardo da Vinci",
  //   option3: "Pablo Picasso",
  //   option4: "Michelangelo",
  //   answer: "Leonardo da Vinci",
  // },
  // {
  //   question: "Which country is known as the Land of the Rising Sun?",
  //   option1: "China",
  //   option2: "Japan",
  //   option3: "India",
  //   option4: "Thailand",
  //   answer: "Japan",
  // },
  // {
  //   question: "What is the chemical symbol for water?",
  //   option1: "Wo",
  //   option2: "Wa",
  //   option3: "H2O",
  //   option4: "W",
  //   answer: "H2O",
  // },
  // {
  //   question: "Who painted the Mona Lisa?",
  //   option1: "Vincent van Gogh",
  //   option2: "Leonardo da Vinci",
  //   option3: "Pablo Picasso",
  //   option4: "Michelangelo",
  //   answer: "Leonardo da Vinci",
  // },
];
